name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: Install cocoapods
      run: gem install cocoapods
    - name: Run ios tests
      run: xcodebuild -project BSImagePicker.xcodeproj -scheme BSImagePicker test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.0' | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run pod lint
      run: pod lib lint --quick
